#!/usr/bin/env python3
"""
tools/text_to_c_array.py

将字符文本渲染为抗锯齿 RGB565 位图，并生成驻留于 Flash (.rodata) 的 C 数组头文件。
参数直接以变量形式配置在 main() 函数中，无需命令行参数。
"""

import os
import sys

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    print("[!] Error: 'Pillow' is required.")
    print("    Install it via: pip install Pillow")
    sys.exit(1)


WORKSPACE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DEFAULT_FONT_CANDIDATES = [
    os.path.join(
        WORKSPACE_ROOT,
        "pomelo-firmware/firmware/managed_components/lvgl__lvgl/tests/src/test_files/fonts/Montserrat-Bold.ttf",
    ),
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/truetype/ubuntu/UbuntuSans[wdth,wght].ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
]


def find_default_font():
    for f in DEFAULT_FONT_CANDIDATES:
        if os.path.exists(f):
            return f
    return None


def hex_to_rgb(hex_str):
    hex_str = hex_str.lstrip("#")
    if len(hex_str) == 3:
        hex_str = "".join([c * 2 for c in hex_str])
    return tuple(int(hex_str[i : i + 2], 16) for i in (0, 2, 4))


def rgb_to_rgb565(r, g, b, endian="be"):
    r5 = (r >> 3) & 0x1F
    g6 = (g >> 2) & 0x3F
    b5 = (b >> 3) & 0x1F
    val = (r5 << 11) | (g6 << 5) | b5

    if endian == "be":
        return ((val & 0xFF) << 8) | ((val >> 8) & 0xFF)
    return val


def render_splash_image(
    text="Pomelo UI",
    font_path=None,
    font_size=42,
    fg_color="#FFFFFF",
    accent_color="#FFA000",
    bg_color="#000000",
    padding_x=28,
    padding_y=20,
):
    if not font_path:
        font_path = find_default_font()
    if not font_path or not os.path.exists(font_path):
        raise FileNotFoundError(f"Font file not found: {font_path}")

    font = ImageFont.truetype(font_path, font_size)
    bg_rgb = hex_to_rgb(bg_color)
    fg_rgb = hex_to_rgb(fg_color)
    accent_rgb = hex_to_rgb(accent_color) if accent_color else fg_rgb

    # Vertical metrics
    overall_bbox = font.getbbox(text)
    text_ink_h = overall_bbox[3] - overall_bbox[1]

    # Horizontal metrics with space preservation
    tokens = text.split(" ")
    space_w = font.getlength(" ")
    total_w = 0.0
    words_info = []

    for i, token in enumerate(tokens):
        w = font.getlength(token)
        color = accent_rgb if (i == len(tokens) - 1 and len(tokens) > 1 and accent_color) else fg_rgb
        words_info.append((token, color, w))
        total_w += w
        if i < len(tokens) - 1:
            total_w += space_w

    # Dimensions with 2-pixel alignment (required for CO5300 QSPI controllers)
    canvas_w = int(round(total_w)) + padding_x * 2
    canvas_h = text_ink_h + padding_y * 2
    if canvas_w % 2 != 0:
        canvas_w += 1
    if canvas_h % 2 != 0:
        canvas_h += 1

    img = Image.new("RGB", (canvas_w, canvas_h), color=bg_rgb)
    draw = ImageDraw.Draw(img)

    cur_x = (canvas_w - int(round(total_w))) // 2
    cur_y = (canvas_h - text_ink_h) // 2 - overall_bbox[1]

    for i, (token, color, w) in enumerate(words_info):
        draw.text((cur_x, cur_y), token, font=font, fill=color)
        cur_x += int(round(w))
        if i < len(words_info) - 1:
            cur_x += int(round(space_w))

    return img


def generate_c_header(
    img,
    output_header_path,
    array_name="s_splash_logo",
    endian="be",
    macro_prefix="SPLASH_LOGO",
):
    w, h = img.size
    pixels = img.load()

    os.makedirs(os.path.dirname(os.path.abspath(output_header_path)), exist_ok=True)

    c_lines = []
    c_lines.append("/*")
    c_lines.append(" * Auto-generated by tools/text_to_c_array.py. DO NOT EDIT DIRECTLY.")
    c_lines.append(f" * Dimensions: {w}x{h}, Pixel Format: RGB565 ({endian.upper()}-endian)")
    c_lines.append(f" * Size: {w * h * 2} bytes ({w * h * 2 / 1024:.2f} KB)")
    c_lines.append(" */\n")
    c_lines.append("#pragma once\n")
    c_lines.append("#include <stdint.h>")
    c_lines.append("#ifdef __has_include")
    c_lines.append("#if __has_include(<esp_attr.h>)")
    c_lines.append("#include <esp_attr.h>")
    c_lines.append("#endif")
    c_lines.append("#endif\n")
    c_lines.append("#ifndef RODATA_ATTR")
    c_lines.append("#define RODATA_ATTR")
    c_lines.append("#endif\n")
    c_lines.append(f"#define {macro_prefix}_WIDTH   {w}")
    c_lines.append(f"#define {macro_prefix}_HEIGHT  {h}\n")
    c_lines.append(
        "// Flash-resident (.rodata), 0 RAM consumed when not actively transmitting"
    )
    c_lines.append(
        f"static const uint16_t {array_name}[{w} * {h}] RODATA_ATTR = {{"
    )

    for y in range(h):
        row_hex = []
        for x in range(w):
            r, g, b = pixels[x, y][:3]
            val = rgb_to_rgb565(r, g, b, endian=endian)
            row_hex.append(f"0x{val:04x}")
        for i in range(0, len(row_hex), 12):
            chunk = ", ".join(row_hex[i : i + 12])
            comma = "," if (y < h - 1 or i + 12 < len(row_hex)) else ""
            c_lines.append(f"    {chunk}{comma}")

    c_lines.append("};\n")

    with open(output_header_path, "w", encoding="utf-8") as f:
        f.write("\n".join(c_lines))

    print(f"[+] Generated C header: {output_header_path} ({w}x{h}, {w * h * 2} bytes)")


def main():
    # =========================================================================
    # Configuration / 参数配置（直接在此修改变量，无需命令行参数）
    # =========================================================================
    TEXT = "Pomelo UI"                      # 要显示的文字
    FONT_SIZE = 42                          # 字体大小 (pt)
    FG_COLOR = "#FFFFFF"                    # 主体文字颜色（纯白）
    ACCENT_COLOR = "#FFFFFF"                # 结尾强调文字颜色（柚子金橙），若为 None 则全部同色
    BG_COLOR = "#000000"                    # 背景颜色（AMOLED 纯黑）
    PADDING_X = 28                          # 水平留白内边距
    PADDING_Y = 20                          # 垂直留白内边距
    ENDIAN = "be"                           # RGB565 字节序 ("be" 大端序适合 SPI 直接 DMA)

    FONT_PATH = find_default_font()         # 字体路径，默认自动匹配 Montserrat-Bold
    ARRAY_NAME = "s_splash_logo"            # C 数组变量名
    OUTPUT_HEADER = os.path.join(           # 输出 C 头文件路径
        WORKSPACE_ROOT,
        "pomelo-firmware/firmware/components/board_hal/splash_logo.h",
    )
    PREVIEW_PATH = os.path.join(            # 预览图路径
        WORKSPACE_ROOT,
        "tools/splash_preview.png",
    )

    # =========================================================================
    # Execution
    # =========================================================================
    if not FONT_PATH or not os.path.exists(FONT_PATH):
        print(f"[!] Error: Font not found: {FONT_PATH}")
        sys.exit(1)

    print(f"[*] Rendering text: '{TEXT}' using font: {FONT_PATH} (size {FONT_SIZE})")
    img = render_splash_image(
        text=TEXT,
        font_path=FONT_PATH,
        font_size=FONT_SIZE,
        fg_color=FG_COLOR,
        accent_color=ACCENT_COLOR,
        bg_color=BG_COLOR,
        padding_x=PADDING_X,
        padding_y=PADDING_Y,
    )

    w, h = img.size
    print(f"[*] Rendered image size: {w}x{h}")

    if PREVIEW_PATH:
        os.makedirs(os.path.dirname(os.path.abspath(PREVIEW_PATH)), exist_ok=True)
        img.save(PREVIEW_PATH)
        print(f"[+] Saved preview image: {PREVIEW_PATH}")

    generate_c_header(
        img=img,
        output_header_path=OUTPUT_HEADER,
        array_name=ARRAY_NAME,
        endian=ENDIAN,
    )
    print("[*] Done!")


if __name__ == "__main__":
    main()
